#ifndef _APP_HANDLER_H_
#define _APP_HANDLER_H_


#include "Typedef.h"


#define DISPLAY_TIME_1S_FLAG             1
#define DISPLAY_TIME_3S_FLAG             3
#define DISPLAY_TIME_5S_FLAG             5
#define DISPLAY_TIME_8S_FLAG             8
#define DISPLAY_TIME_10S_FLAG           10
#define DISPLAY_TIME_30S_FLAG           30
#define DISPLAY_STATE_NO_CHANGE     0xFF


extern uint8 AppTaskId;


typedef enum{
	MSG_HANDLER_BEGIN = 1,
	MSG_HANDLER_END,
	MSG_HANDLER_RESUME,

	MSG_TOUCH_UP_SHORTKEY_PRESS,					/*触摸 单击 按下*/
	MSG_TOUCH_UP_SHORTKEY,							/*触摸 单击*/
	MSG_TOUCH_DOWN_SHORTKEY,
	MSG_LEFTDOWN_SHORTKEY,							/*左键 单击*/
	MSG_RIGHTDOWN_SHORTKEY,							/*右键 单击*/

	MSG_TOUCH_UP_DOUBLE_SHORTKEY_FOR_RESUME,		/*触摸 双击 休眠唤醒*/
	MSG_TOUCH_UP_DOUBLE_SHORTKEY,					/*触摸 双击*/
	MSG_TOUCH_DOWN_DOUBLE_SHORTKEY,
	MSG_LEFTDOWN_DOUBLE_SHORTKEY,					/*左键 双击*/
	MSG_RIGHTDOWN_DOUBLE_SHORTKEY,					/*右键 双击*/

	MSG_TOUCH_UP_FLICK,								/*上*/
	MSG_TOUCH_DOWN_FLICK,							/*下*/
	MSG_TOUCH_DOWN_UP_FLICK,						/*左*/
	MSG_TOUCH_UP_DOWN_FLICK,						/*右*/
	MSG_TOUCH_LONGKEY,								/*触摸 长按*/	
	MSG_TOUCH_LONGKEY_UP,							/*触摸 长按松开*/	
	MSG_LEFTDOWN_LONGKEY,							/*左键 长按*/
	MSG_LEFTDOWN_LONGKEY_5S,						/*左键 长按5秒*/
	MSG_RIGHTDOWN_LONGKEY,							/*右键 长按*/	
	MSG_RIGHTDOWN_HOLDKEY,							/*右键 HOLD*/	
	MSG_RIGHTDOWN_LONGKEY_UP,						/*右键 长按松开*/
	MSG_RIGHTDOWN_HOLDKEY_UP,						/*右键 HOLD松开*/

	MSG_DISPLAY,
	MSG_SHOW_BT_CONNECTING,

	MSG_SMS_NOTIFY,
	MSG_INCOMING_CALL_NOTIFY,
	MSG_MISSED_CALL_COUNT,
	MSG_E_MAIL_NOTIFY,
	MSG_DAILY_SCHEDULE_NOTIFY,
	MSG_SOCIAL_NOTIFY,
	MSG_SMS_NOTIFY_UNLOAD,
	MSG_INCOMING_CALL_UNLOAD,
	MSG_MISSED_CALL_COUNT_UNLOAD,
	MSG_E_MAIL_NOTIFY_UNLOAD,
	MSG_DAILY_SCHEDULE_NOTIFY_UNLOAD,
	MSG_SOCIAL_NOTIFY_UNLOAD,

	MSG_MEMORY_CHANGE,
	MSG_USER_REMIND,
	MSG_SIT_REMIND,
	MSG_BLE_DATA_RECIEVED,
	MSG_BLE_DISCONNECT,
	MSG_BLE_CONNECTED,
	MSG_BC5_DISCONNECT,
	MSG_CHARGE_START,
	MSG_CHARGE_STOP,
	MSG_DATE_UPDATE,
	MSG_DATE_TIME_UPDATE,
	MSG_DATE_TIME_FORMAT_UPDATE,
	MSG_LOW_BATTERY,
	MSG_POWER_OFF_BATTERY,
	MSG_UPDATE_BATTERY,
	MSG_UART0_DATA_INVALID,
	MSG_BC5_BT_CHANGE,

	MSG_CALL_SKIP_KEY_FALSE,
	MSG_CALL_TIME_DISPLAY,
	MSG_CALL_STATE_LOAD_UNKNOW_CALL,                                        /*Load 未知来电*/
	MSG_CALL_STATE_LOAD_FIRST_CALL,                                            /*Load 第一来电*/
	MSG_CALL_STATE_LOAD_SECOND_CALL,                                         /*Load 第二来电*/
	MSG_CALL_STATE_IDLE,                                                                   /*挂所有通话*/
	MSG_CALL_STATE_ONE_CALL_TALKING,                                          /*接通第一通话*/
	MSG_CALL_STATE_SECOND_CALL_INCOMING_FIRST_CALL_END,   /*第二来电时第一通话被挂*/
	MSG_CALL_STATE_SECOND_CALL_INCOMING_END,                        /*挂第二*/
	MSG_CALL_STATE_ANSWER_SECOND_CALL_FIRST_CALL_END,      /*挂第一接第二*/
	MSG_CALL_STATE_TWO_CALL_TALKING,                                         /*接通第二路通话*/
	MSG_CALL_STATE_TWO_CALL_TALKING_ACTIVE_END,                  /*被挂掉当前*/
	MSG_CALL_STATE_TWO_CALL_TALKING_HOLD_END,                     /*主动挂掉当前或被挂掉保持*/
	MSG_CALL_STATE_OUT_GOING,
	MSG_CALL_SEND_CMD_AGAIN,
	MSG_CALL_ID_CLEAR,
	MSG_CALL_STATE_FORCE_IDLE,    
	MSG_CALL_DISPLAY_NUMBER_ROLL,

	MSG_BC5_SIRI_OPEN,
	MSG_BC5_SIRI_DISPLAY_OPEN,
	MSG_BC5_SIRI_CLOSE,

	MSG_SYNCING_START,
	MSG_SYNCING_STOP,
	MSG_GOAL_OVER_NOTIFY,
	MSG_UART0_READY,
	MSG_BT_NAME_RX,
	MSG_BT_ADDR_RX,
	MSG_BC5_VOLUME_CHANGE,
	MSG_BC5_RING_MODE_CHANGE,
	MSG_BC5_SW_VERSION_RX,
	MSG_ALARM,
	MSG_SETUP_END,

	MSG_SETUP_QUIT,
	MSG_SYSTEM_SUSPEND,
	MSG_SYSTEM_RESUME,
	MSG_SYSTEM_FACTORY_SET_STATE,
	MSG_DISCONNECT_QUIT_STATE,
	MSG_DISPALY_BATTERY_FULL_QUIT,
	MSG_DISPLAY_BATTERY_ROLL_STATE,
	MSG_DISPLAY_BATTERY_STATE,
	MSG_DISPLAY_POWEROFF_STATE,
	MSG_DISPLAY_RING_MODE_STATE,
	MSG_SSD13XX_EXIT_SLEEP,
	MSG_BC5_RECONNECT_TIMEOUT_STATE,
	MSG_BLE_ADVERTISING_CLOSE_STATE,

	MSG_BT_CONNECTING_HANDLER_TIMEOUT,
	MSG_BT_PAIR_RESULT_HANDLER_TIMEOUT,
	MSG_VOLUME_HANDLER_TIMEOUT,
	MSG_SIRI_HANDLER_TIMEOUT,
	MSG_SIRI_DISPLAY_OPEN,
	MSG_SLEEP_MODE_CHANGE,
	MSG_SLEEP_EXIT_TIMEOUT,
	MSG_RINGMODE_HANDLER_TIMEOUT,
	MSG_CLOCKDEL_HANDLER_TIMEOUT,
	MSG_PHONECALLOUT_HANDLER_TIMEOUT,
	MSG_PHONECALLOUT_HANDLER_CANCEL,
	MSG_PHONECALLOUT_HANDLER_NORSP,
	MSG_PHONERING_HANDLER_TIMEOUT,
	MSG_PHONECALL_HANDLER_TIMEOUT,
	MSG_REMIND_HANDLER_TIMEOUT,
	MSG_ANCS_SMS_DISPLAY_TITLE,
	MSG_ANCS_SMS_DISPLAY_MESSAGE,
	MSG_ANCS_SMS_SHOW_NEXT_LETTER,
	MSG_ANCS_SMS_QUERY_DOT,
	MSG_SEND_SOCIAL_MESSAGE,
	MSG_ANCS_SMS_QUERY_UID,
	MSG_ANCS_SMS_RESET_SENDER,
	MSG_ANCS_INCOMINGCALL_LATER_GET,
	MSG_ANCS_MISSCALL_LATER_GET,
	MSG_ANCS_EMAIL_LATER_GET,
	MSG_ANCS_SCHEDULE_LATER_GET,
	MSG_ANCS_CONNECTED_GET_ALL,
	MSG_ANCS_SMS_LATER_GET,
	MSG_ANCS_REQUIRE_DISPLAY,
	MSG_ANCS_CANCEL_DISPLAY,
	MSG_ANCS_SAVE_TO_FLASH,
	
	MSG_BUTTON_POWERUP_BC5_ENABLE,
	MSG_BC5_OFF_RESET,
	MSG_BC5_ON_RESET,
	MSG_BC5_SUSPEND,
	MSG_SLEEP_CLOSE_BT,
	MSG_SLEEP_OPEN_BT,
	MSG_STOP_INCOMING_TONE,
	MSG_BLE_BOND_CHOOSE,
	MSG_BLE_BOND_CHOOSE_QUIT,
	MSG_BLE_BOND_CHOOSE_TIMEOUT,

	MSG_SLEEP_MODE_FORCE_EXIT,
	MSG_SLEEP_MODE_START,
	MSG_SLEEP_MODE_EXIT,
	MSG_SLEEP_EXIT_BC5_OPEN,
	MSG_FONT_DISPLAY_NEXT_LETTER,
	MSG_FONT_BUF_DISPLAY_NEXT_LETTER,
	MSG_OTA,
	MSG_OTA_FAIL,
	MSG_OTA_SUCCESS,
	MSG_SIRI_SEND_CMD_AGAIN,
	MSG_VOL_SET_CMD_AGAIN,
	MSG_RING_MODE_CMD_AGAIN,
	MSG_VOL_SET,
	MSG_SWITCH_CALL,
	MSG_UPDATE_FONT_LIB,
	MSG_UPDATE_FONT_LIB_SEND_CMD,
	MSG_UPDATE_FONT_LIB_SUCCESS,
	MSG_UPDATE_FONT_LIB_FAIL,
	MSG_UPDATE_FONT_LIB_TIMEOUT,
	MSG_PAY_SYNCING_START,
	MSG_PAY_SYNCING_STOP,
	MSG_LED_TEST,
	MSG_NFC_TEST,
	MSG_GET_CSN,
	MSG_PAY_SYNCING_HANDLER_TIMEOUT,
	MSG_NFC_HANDLER_TIMEOUT,
	MSG_NFC_ACTION_OPEN,
	MSG_NFC_ACTION_CLOSE,
	MSG_POWER_ON_CMD,
	MSG_POWER_OFF_CMD,
	MSG_APDU_CMD,
	MSG_VIBRATE_CMD,
	MSG_APPLICATION_BLOCK_UNBLOCK,
	MSG_READ_TRANSACTION_LOG,
	MSG_WAIT_BLE_PACKETS_TIMEOUT,
	MSG_SET_BOOSTER_PARAMETERS,
	MSG_GET_BOOSTER_PARAMETERS,


	MSG_REPEAT_SPORT_DISPLAY,
	MSG_REPEAT_SCD_DISPLAY,
	MSG_CAMERA_CONTROL,
	MSG_SEARCH_CONTROL,

	MSG_ADVERTISER_START,
	MSG_ADVERTISER_STOP,
	MSG_SCANNER_START,
	MSG_SCANNER_STOP,
	MSG_DEVICESCOM_REPEAT,
	
	MSG_UPLOAD_REMINDS,
	MSG_NOTIFYCATION_ACC_BALANCE,
	MSG_MUSIC_NOTIC,
	MSG_CAMERA_NOTIC,
	MSG_OPEN_CAMERA_NOTIC,
	MSG_SEARCH_NOTIC,
	

	MSG_DEVICE_SEARCH_TIMEOUT,
	MSG_REPEAT_DEVICE_SEARCH_DISPLAY,
	MSG_DEVICE_ADDFRIEND_TIMEOUT,
	MSG_DEVICE_ADDFRIEND_DISPLAY_TIMEOUT,
	MSG_REPEAT_DEVICE_REQUEST_DISPLAY,
	MSG_DEVICE_ADDFRIEND_RSP_TIMEOUT,
	MSG_DEVICE_RECEIVE_ADDFRIEND_TIMEOUT,
	MSG_REPEAT_DEVICE_MOTO_DISPLAY,
	MSG_REPEAT_DEVICE_EMOTION_DISPLAY,	
	MSG_REPEAT_DELETING_DEVICES_DISPLAY,
	MSG_DELETE_DEVICES_TIMEOUT,
	MSG_REPEAT_REC_DELETING_DEVICES,
	MSG_RECEIVE_EXP_TIMEOUT,
	MSG_RECEIVE_MOTO_TIMEOUT,
	MSG_RECEIVE_DEL_TIMEOUT,
	
	MSG_GET_SCAN_NAME,	
	MSG_GET_SCAN_ADD_FRIENDS,
	MSG_GET_SCAN_ADD_FRIENDS_REC,
	MSG_GET_SCAN_ADD_FRIENDS_OK,
	MSG_GET_SCAN_ADD_FRIENDS_FAIL,
	MSG_GET_SCAN_DEL_FRIENDS,
	MSG_GET_SCAN_DEL_FRIENDS_OK,
	MSG_GET_SCAN_DEL_FRIENDS_FAIL,	
	MSG_GET_SCAN_MOTO,
	MSG_GET_SCAN_MOTO_OK,
	MSG_GET_SCAN_MOTO_FAIL,
	MSG_GET_SCAN_EXP,
	MSG_GET_SCAN_EXP_OK,
	MSG_GET_SCAN_EXP_FAIL,	

	MSG_WAKEUP_ACTION,
	MSG_SECONDS_TIMER_EVENT,
	MSG_SERIALNUM_TIMEOUT,
	MSG_DELAY_ADVERTISE_INIT,
	
	MSG_MUSIC_NOTIC_CONNECTING,
	MSG_MUSIC_CONTROL_TIMEOUT,
	MSG_MUSIC_HANDLER_TIMEOUT,
	MSG_RESET_PROGRESS_UPDATE,
	MSG_TIMER_TIMEOUT,
	MSG_CAMERA_NOTIC_CONNECTING,
	MSG_CAMERA_CONTROL_TIMEOUT,
	MSG_CAMERA_HANDLER_TIMEOUT,
	MSG_SEARCH_NOTIC_CONNECTING,

	MSG_ANCS_REPLAY_SUCCESS,
	MSG_ANCS_REPLAY_FAIL,
	MSG_ANCS_REPLAY_HANDLER_TIMEOUT,
	
	MSG_HR_STATE_CHECK,
	MSG_HR_UPPER_REMIND,
	MSG_HR_LOWER_REMIND,
	MSG_NFC_ANIMATION,
	MSG_NFC_CONSUME,
	MSG_NFC_BALANCE,
	MSG_NFC_LOG,
	MSG_TEST_TP,

	MSG_REFRESH_HR,
	MSG_REFRESH_STEP,
	MSG_SCREEN_DIR_CHG,
	MSG_REMOVE_SLEEP_MONITOR,
	MSG_DISPLAY_BALANCE,
	MSG_OPEN_STEP,
	MSG_BIND_OK,
	MSG_PHONE_PREPARE_NUMBER,
	MSG_SET_BACKLIGHT_DAKR,
	MSG_SAVE_CALLER_ID_TO_FLASH,
	MSG_ACTIVE_NFC,
	MSG_REMOVE_ALL_ANCS,
	MSG_CLEAR_ALL,
	MSG_ClEAR_ANCS_CMD,
	MSG_UNLOADHANDLER_CMD,
	MSG_SYNCING_CHECK_CMD,
	MSG_BC5_STATE_CHANGE,
	MSG_RECOVER_DIAL_NUMBER,
	MSG_RECOVER_DIAL_INCALLNUMBER,
	MSG_FACEBOOK_MESSAGE_IDTITLE,
	MSG_SKYPE_IDTITLE,
	MSG_WHATSAPP_IDTITLE,
	MSG_QQ_IDTITLE,
	MSG_SNAPCHAT_IDTITLE,
	MSG_BIND_END,
	MSG_RESTART_PROGRESS_UPDATE,
	MSG_REFRESH_REMIND,
	MSG_TIME_CLOCK,
	MSG_CAMERA_COUNTDOWN,
	MSG_FORCE_BACK_HOME,							/*返回时间界面*/
	MSG_MOTO_DEFAULT,
	MSG_RECORD_WORK_GO,
	MSG_RECORD_WORK_1S,
	MSG_RECORD_WORK_100MS,
	MSG_UNIT_CHANGED,
	MSG_GOAL_CHANGED,
	MSG_MEDAL,
	MSG_BACKONMAINMENUE,
	MSG_BACKONMAINMENUE_BOND,
	MSG_UNLOADRECORDWORKOUTS,
	MSG_UNLOADSELF_HANDLER_TIMEOUT,
	MSG_EXIT_SLEEP_HANDLER_TIMEOUT,
}MsgType;

typedef enum{
    RET_MSG_HANDLED,
    RET_MSG_UNHANDLED,
    RET_MSG_UNLOAD, 
}HandlerRet;

#if 0
typedef uint16 (*pHandlerFun)(MsgType msg, int iParam, void *pContext);

typedef struct __Handler{
    pHandlerFun pHandler;
    void *pParam;
}Handler;
#endif

#define INVALID_HANDLER_ID 0

typedef uint16 (*pHandlerFun)(MsgType msg, int iParam, void *pContext);
typedef unsigned int HandlerId;

struct  HandlerList
{
    struct HandlerList *pPrev;
    struct HandlerList *pNext;
    pHandlerFun pHandler;
    HandlerId Id;
    void *pParam;
};

uint16 AppEventHandler(uint8 task_id,uint16 events);

uint8 GetAppTaskId(void);

uint8 SendMsg(MsgType msgType);

void AppInitTask(uint8 task_id);

HandlerId LoadHandler (pHandlerFun pFun, void *pData);

void UnloadHandler (HandlerId handlerId);

void UnloadHandler_WithoutDisplay (HandlerId handlerId);

void UnloadMultiHandler (void);

void HandlerMsg(MsgType msgType, int iParam);

bool CheckpCurrentHandler(HandlerId Id);

bool PreHandler(MsgType message);

bool PutTheHandlerOnTop(HandlerId handlerId);

void CleanAppTaskMessage(void);

#endif


